name: Project CI (Frontend & Backend)

on:
  push:
    branches: [main, "dev"]
  pull_request:
    branches: [main, "dev"]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: Backend/package-lock.json

      - name: Install BE dependencies
        run: npm install
        working-directory: ./Backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./Backend

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: Frontend/package-lock.json

      - name: Install FE dependencies
        run: npm install
        working-directory: ./Frontend

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./Frontend
